package resolver_admin

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	generated_admin "e-learning/src/graph/generated/admin"
	graph_model "e-learning/src/graph/generated/model"
	"fmt"
)

// Attendance is the resolver for the attendance field.
func (r *queryResolver) Attendance(ctx context.Context, userID string) ([]graph_model.Attendance, error) {
	panic(fmt.Errorf("not implemented: Attendance - attendance"))
}

// Query returns generated_admin.QueryResolver implementation.
func (r *Resolver) Query() generated_admin.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
