package resolver_admin

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	generated_admin "e-learning/src/graph/generated/admin"
	graph_model "e-learning/src/graph/generated/model"
	"fmt"
)

// FindAccountByID is the resolver for the findAccountByID field.
func (r *entityResolver) FindAccountByID(ctx context.Context, id string) (*graph_model.Account, error) {
	panic(fmt.Errorf("not implemented: FindAccountByID - findAccountByID"))
}

// Entity returns generated_admin.EntityResolver implementation.
func (r *Resolver) Entity() generated_admin.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
