package resolver_admin

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	generated_admin "e-learning/src/graph/generated/admin"
	graph_model "e-learning/src/graph/generated/model"
	"fmt"
)

// AddOrder is the resolver for the addOrder field.
func (r *mutationResolver) AddOrder(ctx context.Context, data graph_model.OrderAdd) (*graph_model.Order, error) {
	// input := &service_order.OrderAddCommand{
	// 	UserID: data.UserID,
	// }
	// result, err := service_order.OrderAdd(ctx, input)
	// if err != nil {
	// 	return &graph_model.Order{}, err
	// }
	// return result.ConvertToModelGraph(), nil
	panic(fmt.Errorf("not implemented: FindAttendanceByID - findAttendanceByID"))
}

// Mutation returns generated_admin.MutationResolver implementation.
func (r *Resolver) Mutation() generated_admin.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
