package resolver_admin

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	service_schedules "e-learning/src/service/schedules"
)

// SchedulesAdd is the resolver for the schedulesAdd field.
func (r *mutationResolver) SchedulesAdd(ctx context.Context, data *graph_model.SchedulesAdd) ([]graph_model.Schedules, error) {
	input := &service_schedules.SchedulesAddCommand{
		ClassID:       data.ClassID,
		Description:   data.Description,
		DayOfWeek:     data.DayOfWeek,
		SchedulesType: data.SchedulesType,
		StartDate:     data.StartDate,
		EndDate:       data.EndDate,
		StartTime:     data.StartTime,
		EndTime:       data.EndTime,
	}

	result, err := service_schedules.SchedulesAdd(ctx, input)
	if err != nil {
		return nil, err
	}
	var schedulesList []graph_model.Schedules
	for _, s := range result {
		schedulesList = append(schedulesList, graph_model.Schedules{
			ID:            s.ID,
			Description:   s.Description,
			StartTime:     s.StartTime,
			EndTime:       s.EndTime,
			DayOfWeek:     s.DayOfWeek,
			Day:           s.Day,
			SchedulesType: s.SchedulesType,
			Class: &graph_model.Class{
				ID:        s.ClassID,
				ClassName: s.ClassName,
			},
		})
	}

	return schedulesList, nil
}

// SchedulesDelete is the resolver for the schedulesDelete field.
func (r *mutationResolver) SchedulesDelete(ctx context.Context, data *graph_model.SchedulesDelete) (bool, error) {
	input := &service_schedules.SchedulesDeleteCommand{
		ID: data.ID,
	}

	err := service_schedules.SchedulesDelete(ctx, input)
	if err != nil {
		return false, err
	}

	return true, nil
}

// SchedulesUpdate is the resolver for the schedulesUpdate field.
func (r *mutationResolver) SchedulesUpdate(ctx context.Context, data *graph_model.SchedulesUpdate) (*graph_model.Schedules, error) {
	input := &service_schedules.SchedulesUpdateCommand{
		ID:          data.ID,
		Description: data.Description,
		// DayOfWeek:     data.DayOfWeek,
		// StartDate:     data.StartDate,
		// EndDate:       data.EndDate,
		SchedulesType: data.SchedulesType,
		StartTime:     data.StartTime,
		EndTime:       data.EndTime,
	}

	res, err := service_schedules.SchedulesUpdate(ctx, input)
	if err != nil {
		return nil, err
	}
	return res.ConvertToModelGraph(), nil
}

// SchedulesList is the resolver for the schedulesList field.
func (r *queryResolver) SchedulesList(ctx context.Context) ([]graph_model.Schedules, error) {
	result, err := service_schedules.SchedulesGetList(ctx, nil)
	if err != nil {
		return nil, err
	}
	var schedulesList []graph_model.Schedules
	for _, s := range result {
		schedulesList = append(schedulesList, graph_model.Schedules{
			ID:            s.ID,
			Description:   s.Description,
			StartTime:     s.StartTime,
			EndTime:       s.EndTime,
			Day:           s.Day,
			DayOfWeek:     s.DayOfWeek,
			SchedulesType: s.SchedulesType,
			Class: &graph_model.Class{
				ID:        s.ClassID,
				ClassName: s.ClassName,
			},
		})
	}

	return schedulesList, nil
}
