package resolver_admin

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	"fmt"
)

// TuitionAdd is the resolver for the tuitionAdd field.
func (r *mutationResolver) TuitionAdd(ctx context.Context, data *graph_model.TuitionAdd) (*graph_model.Tuition, error) {
	panic(fmt.Errorf("not implemented: TuitionAdd - tuitionAdd"))
}

// Tuition is the resolver for the tuition field.
func (r *queryResolver) Tuition(ctx context.Context, userID string) ([]graph_model.Tuition, error) {
	panic(fmt.Errorf("not implemented: Tuition - tuition"))
}
