package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	generated_user "e-learning/src/graph/generated/user"
	"fmt"
)

// AccountMe is the resolver for the accountMe field.
func (r *queryResolver) AccountMe(ctx context.Context) (*graph_model.Account, error) {
	panic(fmt.Errorf("not implemented: AccountMe - accountMe"))
}

// Query returns generated_user.QueryResolver implementation.
func (r *Resolver) Query() generated_user.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
