package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	service_tuition "e-learning/src/service/tuition"
)

// Tuition is the resolver for the tuition field.
func (r *queryResolver) Tuition(ctx context.Context, userID string) (*graph_model.Tuition, error) {
	input := &service_tuition.TuitionByIDCommand{
		UserID: userID,
	}
	res, err := service_tuition.TuitionGetByID(ctx, input)
	if err != nil {
		return nil, err
	}
	return res.ConvertToModelGraph(), nil
}
