package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	service_tuition "e-learning/src/service/tuition"

	"github.com/99designs/gqlgen/graphql"
)

// Tuition is the resolver for the tuition field.
func (r *queryResolver) Tuition(ctx context.Context, userID string) (*graph_model.Tuition, error) {
	input := &service_tuition.TuitionByIDCommand{
		UserID: userID,
	}
	res, err := service_tuition.TuitionGetByID(ctx, input)
	if err != nil {
		return nil, err
	}
	return res.ConvertToModelGraph(), nil
}

// TuitionPagination is the resolver for the tuitionPagination field.
func (r *queryResolver) TuitionPagination(ctx context.Context, page int, limit int, orderBy *string, search map[string]interface{}) (*graph_model.TuitionPagination, error) {
	input := &service_tuition.TuitionPaginationCommand{
		Page:  page,
		Limit: limit,
	}

	if orderBy != nil {
		input.OrderBy = *orderBy
	}

	if search != nil {
		input.Search = search
	}

	total, result, err := service_tuition.TuitionPagination(ctx, input)
	if err != nil {
		if graphql.GetErrors(ctx) == nil {
			return nil, err
		}
		return nil, nil
	}

	tuitions := make([]graph_model.Tuition, 0)
	for i := 0; i < len(result); i++ {
		tuitions = append(tuitions, *result[i].ConvertToModelGraph())
	}

	return &graph_model.TuitionPagination{
		Rows: tuitions,
		Paging: graph_model.Pagination{
			CurrentPage: page,
			Limit:       limit,
			TotalPages:  CalculateTotalPage(total, limit),
			Total:       total,
		},
	}, nil
}
