package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	"fmt"
)

// UserInforMe is the resolver for the userInforMe field.
func (r *queryResolver) UserInforMe(ctx context.Context) (*graph_model.UserInfor, error) {
	panic(fmt.Errorf("not implemented: UserInforMe - userInforMe"))
}
