package resolver_user

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.44

import (
	"context"
	graph_model "e-learning/src/graph/generated/model"
	service_user "e-learning/src/service/user"
)

// UserMe is the resolver for the userMe field.
func (r *queryResolver) UserMe(ctx context.Context, userID string) (*graph_model.User, error) {
	input := &service_user.UserByIDCommand{
		UserID: userID,
	}

	result, err := service_user.UserByID(ctx, input)
	if err != nil {
		return &graph_model.User{}, err
	}

	return result.ConvertToModelGraph(), nil
}
